"""What Posteryard needs from a media server. Plex and Jellyfin both answer with Plex-shaped items:
`ratingKey`, `type` (movie, show, season, episode, collection), `title`, `index`, `parentIndex`,
`parentRatingKey`, `grandparentRatingKey`, `Guid`, `addedAt`, `Label`, `librarySectionID`,
`librarySectionTitle` and `Media` with Plex stream fields.
"""

import re
from collections.abc import Iterable, Mapping
from typing import Any, Literal, Protocol

Item = Mapping[str, Any]
Target = Literal["poster", "art", "thumb"]
ITEM_KEY = re.compile(r"^(\d{1,12}|[0-9a-f]{32})$")


def is_item_key(text: str) -> bool:
    """A Plex rating key (digits) or a Jellyfin item id (32 hex digits)."""
    return bool(ITEM_KEY.match(text))


class MediaServer(Protocol):
    url: str
    name: str

    def sections(self) -> list[Item]: ...
    def item(self, rating_key: str) -> Item | None: ...
    def children(self, rating_key: str) -> list[Item]: ...
    def section_items(self, section_key: str, kind: str, **filters: Any) -> Iterable[Item]: ...
    def changed_since(self, section_key: str, kind: str, since: int) -> list[Item]: ...
    def newest_added(self, section_key: str, kind: str, **filters: Any) -> int | None: ...
    def selected(self, rating_key: str, target: Target) -> str | None: ...
    def upload(self, rating_key: str, target: Target, jpeg: bytes) -> str: ...
    def poster_bytes(self, item: Item) -> bytes: ...
    def remove_label(self, item: Item, label: str) -> None: ...
    def lock(self, item: Item, target: Target) -> None: ...
    def restore(self, item: Item, target: Target) -> None: ...
    def collection_children(self, rating_key: str) -> list[Item]: ...
    def create_collection(self, section_key: str, kind: str, title: str, rating_keys: list[str]) -> str: ...
    def add_to_collection(self, rating_key: str, members: list[str]) -> None: ...
    def remove_from_collection(self, rating_key: str, member: str) -> None: ...
    def delete_collection(self, rating_key: str) -> None: ...
    def set_label(self, section_key: str, kind: str, rating_key: str, label: str) -> None: ...


def labels(item: Item) -> set[str]:
    return {str(label.get("tag", "")).lower() for label in item.get("Label") or []}


def tmdb_id(item: Item) -> int | None:
    for guid in item.get("Guid") or []:
        value = str(guid.get("id", ""))
        if value.startswith("tmdb://"):
            return int(value.removeprefix("tmdb://"))
    return None
